// src/api/mockData.ts
// src/api/mockData.ts
import type { Person, SearchResponse } from "@/types/person";

export const mockPeople: Person[] = [
  {
    id: 1,
    firstname: "DON",
    lastname: "ALESHIRE",
    middlename: "L",
    name_suff: null,
    dob: "19480701",
    address: "370 SHAMROCK ROAD",
    city: "BRANDENBURG",
    county_name: "MEADE",
    st: "KY",
    zip: "40108",
    ssn: null,
    phone1: "5024223993",
  },
  {
    id: 2,
    firstname: "DON",
    lastname: "ALESHIRE",
    middlename: "L",
    name_suff: "None",
    dob: null,
    address: "1632 OLD EKRON RD",
    city: "BRANDENBURG",
    county_name: "MEADE",
    st: "KY",
    zip: "40108",
    ssn: null,
    phone1: null,
  },
  {
    id: 3,
    firstname: "JANE",
    lastname: "DOE",
    middlename: "M",
    name_suff: null,
    dob: "19850515",
    address: "123 MAIN ST",
    city: "NEW YORK",
    county_name: "NEW YORK",
    st: "NY",
    zip: "10001",
    ssn: null,
    phone1: "2125551234",
  },
  {
    id: 4,
    firstname: "JOHN",
    lastname: "SMITH",
    middlename: null,
    name_suff: "JR",
    dob: "19900310",
    address: "456 ELM ST",
    city: "LOS ANGELES",
    county_name: "LOS ANGELES",
    st: "CA",
    zip: "90001",
    ssn: null,
    phone1: "3105551234",
  },
  {
    id: 5,
    firstname: "MARY",
    lastname: "JOHNSON",
    middlename: "ANN",
    name_suff: null,
    dob: "19750820",
    address: "789 OAK AVE",
    city: "CHICAGO",
    county_name: "COOK",
    st: "IL",
    zip: "60601",
    ssn: null,
    phone1: "3125555678",
  },
  {
    id: 6,
    firstname: "ROBERT",
    lastname: "WILLIAMS",
    middlename: "JAMES",
    name_suff: "SR",
    dob: "19601205",
    address: "321 PINE ST",
    city: "HOUSTON",
    county_name: "HARRIS",
    st: "TX",
    zip: "77001",
    ssn: null,
    phone1: "7135559012",
  },
  {
    id: 7,
    firstname: "PATRICIA",
    lastname: "BROWN",
    middlename: "LYNN",
    name_suff: null,
    dob: "19880918",
    address: "654 MAPLE DR",
    city: "PHOENIX",
    county_name: "MARICOPA",
    st: "AZ",
    zip: "85001",
    ssn: null,
    phone1: "6025553456",
  },
  {
    id: 8,
    firstname: "MICHAEL",
    lastname: "DAVIS",
    middlename: "ALLEN",
    name_suff: null,
    dob: "19920422",
    address: "987 CEDAR LN",
    city: "PHILADELPHIA",
    county_name: "PHILADELPHIA",
    st: "PA",
    zip: "19101",
    ssn: null,
    phone1: "2155557890",
  },
];

export const mockStates = ["KY", "NY", "CA", "IL", "TX", "AZ", "PA"];
